name: graphql_fetch
description: a simple graphql client for dart
version: 0.0.3
homepage: https://github.com/spacedragon/graphql-fetch
author: draco <allendragon@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  http: ^0.11.3+16
  meta: ^1.1.2

#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
