name: graphql_fetch_generator
description: The code generator for graphql_fetch.
version: 0.0.3
homepage: https://github.com/spacedragon/graphql-fetch
author: draco <allendragon@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  graphql_fetch: 
    git:
      url: https://github.com/metaflowltd/graphql-fetch.git
      path: client
  graphql_parser: ^1.0.0+1
  code_builder: ^3.0.3
  json_object: "^1.0.19+1"
  logging: ^0.11.3+1
  dart_style: ^1.0.8
  build: "^0.11.0"
  build_runner: "^0.6.0+1"
  path: ^1.5.0
  glob: ^1.1.5
  barback: ^0.15.2+13
  build_barback: ^0.4.0

dev_dependencies:
  test: ^0.12.0

dependency_overrides:
  graphql_fetch:
    path: ../client
